"""add_retrieval_quality_to_feedback

Revision ID: ea80f9db252e
Revises: fd27d02634cd
Create Date: 2026-07-04 16:44:57.371240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea80f9db252e'
down_revision: Union[str, Sequence[str], None] = 'fd27d02634cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_triples_doc_id'), table_name='kg_triples')
    op.drop_index(op.f('ix_kg_triples_object'), table_name='kg_triples')
    op.drop_index(op.f('ix_kg_triples_subject'), table_name='kg_triples')
    op.drop_table('kg_triples')
    op.drop_index(op.f('ix_qa_cache_query_hash'), table_name='qa_cache')
    op.drop_table('qa_cache')
    op.drop_index(op.f('ix_document_versions_doc_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('conversation_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('query', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('feedback', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('judge_supported', mysql.FLOAT(), nullable=True),
    sa.Column('judge_halluc', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('document_versions',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('doc_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minio_object', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name=op.f('document_versions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_document_versions_doc_id'), 'document_versions', ['doc_id'], unique=False)
    op.create_table('qa_cache',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cache_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False, comment='缓存键: qa:{model}:{normalized}'),
    sa.Column('model_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('query_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False, comment='MD5(cache_key) 精确匹配'),
    sa.Column('query_normalized', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='归一化后的问题'),
    sa.Column('query_original', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='用户原始问题'),
    sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='问答结果 JSON（与 Redis 缓存同结构）'),
    sa.Column('retrieval_sources', mysql.JSON(), nullable=True, comment='引用来源'),
    sa.Column('confidence', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False),
    sa.Column('hallucination_rate', mysql.FLOAT(), nullable=False),
    sa.Column('hit_count', mysql.INTEGER(), autoincrement=False, nullable=False, comment='累计命中次数'),
    sa.Column('ttl_seconds', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False, comment='过期时间'),
    sa.Column('last_hit_at', mysql.DATETIME(), nullable=True, comment='最后一次命中时间'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('is_deleted', mysql.INTEGER(), autoincrement=False, nullable=False, comment='软删标记'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_qa_cache_query_hash'), 'qa_cache', ['query_hash'], unique=True)
    op.create_table('kg_triples',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('subject', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('relation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('object', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('doc_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('doc_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_kg_triples_subject'), 'kg_triples', ['subject'], unique=False)
    op.create_index(op.f('ix_kg_triples_object'), 'kg_triples', ['object'], unique=False)
    op.create_index(op.f('ix_kg_triples_doc_id'), 'kg_triples', ['doc_id'], unique=False)
    # ### end Alembic commands ###
